import Header from "@/components/Header/Header";
import "./globals.css";

export const metadata = {
    title: "Talent Engine",
    description: "Generated by Talent Engine",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Header />
                {children}
            </body>
        </html>
    );
}
